channels:
- anaconda-fusion
- pkgw-forge
- conda-forge
- defaults
dependencies:
- blas=1.1=openblas
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py35_0
- ncurses=5.9=10
- numpy=1.14.0=py35_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pip=9.0.1=py35_1
- python=3.5.5=0
- readline=7.0=0
- scipy=1.0.0=py35_blas_openblas_201
- setuptools=38.5.1=py35_0
- sqlite=3.20.1=2
- tk=8.6.7=0
- wheel=0.30.0=py35_2
- xz=5.2.3=0
- zlib=1.2.11=0
- libgfortran=3.0.0=1
- pip:
  - attrs==17.4.0
  - cvxpy==1.0.0
  - cycler==0.10.0
  - dill==0.2.7.1
  - ecos==2.0.5
  - fastcache==1.0.2
  - future==0.16.0
  - matplotlib==2.1.2
  - multiprocess==0.70.5
  - osqp==0.2.1
  - pandas==0.22.0
  - pluggy==0.6.0
  - py==1.5.2
  - pyparsing==2.2.0
  - pytest==3.4.0
  - python-dateutil==2.6.1
  - pytz==2018.3
  - scikit-learn==0.19.1
  - scs==2.0.2
  - seaborn==0.8.1
  - six==1.11.0
  - toolz==0.9.0